# EXACT match to official NEJM implementation
# This should reproduce their stable training

model:
  n_input_features: 512
  n_units: 768
  rnn_dropout: 0.4
  rnn_trainable: true
  n_layers: 5
  patch_size: 14
  patch_stride: 4

  input_network:
    n_input_layers: 1
    input_layer_sizes:
    - 512
    input_trainable: true
    input_layer_dropout: 0.2

gpu_number: '0'
mode: train
use_amp: true

output_dir: trained_models/official_exact
checkpoint_dir: trained_models/official_exact/checkpoint
init_from_checkpoint: false
init_checkpoint_path: None
save_best_checkpoint: true
save_all_val_steps: false
save_final_model: true
save_val_metrics: true
early_stopping: false
early_stopping_val_steps: 20

num_training_batches: 120000
lr_scheduler_type: cosine
lr_max: 0.005  # OFFICIAL: 0.005 (NOT 0.002!)
lr_min: 0.0001
lr_decay_steps: 120000
lr_warmup_steps: 1000  # OFFICIAL: 1000 (NOT 2000!)
lr_max_day: 0.005
lr_min_day: 0.0001
lr_decay_steps_day: 120000
lr_warmup_steps_day: 1000

beta0: 0.9
beta1: 0.999
epsilon: 0.1  # OFFICIAL: 0.1
weight_decay: 0.001
weight_decay_day: 0.0
seed: 10
grad_norm_clip_value: 10.0
use_fused_adamw: true  # Official uses fused=True
grad_norm_threshold: 40.0
skip_on_explosion: false
extreme_explosion_factor: 5.0

batches_per_train_log: 200
batches_per_val_step: 2000

batches_per_save: 0
log_individual_day_val_PER: true
log_val_skip_logs: false
save_val_logits: true
save_val_data: false

dataset:
  data_transforms:
    # CRITICAL: Official uses MUCH stronger augmentation than we were using
    white_noise_std: 1.0  # OFFICIAL: 1.0 (NOT 0.25!)
    constant_offset_std: 0.2  # OFFICIAL: 0.2 (NOT 0.05!)
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 3
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2

  neural_dim: 512
  batch_size: 48  # TUNED FOR 16GB VRAM: Reduced from 64 to 48 for stable overnight training.
  n_classes: 41
  max_seq_elements: 500
  days_per_batch: 4
  seed: 1
  num_dataloader_workers: 4 # Default for local training
  loader_shuffle: false
  must_include_days: null
  test_percentage: 0.1
  feature_subset: null

  dataset_dir: ../data/hdf5_data_final
  bad_trials_dict: null

  # All 45 sessions
  sessions:
  - t15.2023.08.11
  - t15.2023.08.13
  - t15.2023.08.18
  - t15.2023.08.20
  - t15.2023.08.25
  - t15.2023.08.27
  - t15.2023.09.01
  - t15.2023.09.03
  - t15.2023.09.24
  - t15.2023.09.29
  - t15.2023.10.01
  - t15.2023.10.06
  - t15.2023.10.08
  - t15.2023.10.13
  - t15.2023.10.15
  - t15.2023.10.20
  - t15.2023.10.22
  - t15.2023.11.03
  - t15.2023.11.04
  - t15.2023.11.17
  - t15.2023.11.19
  - t15.2023.11.26
  - t15.2023.12.03
  - t15.2023.12.08
  - t15.2023.12.10
  - t15.2023.12.17
  - t15.2023.12.29
  - t15.2024.02.25
  - t15.2024.03.03
  - t15.2024.03.08
  - t15.2024.03.15
  - t15.2024.03.17
  - t15.2024.04.25
  - t15.2024.04.28
  - t15.2024.05.10
  - t15.2024.06.14
  - t15.2024.07.19
  - t15.2024.07.21
  - t15.2024.07.28
  - t15.2025.01.10
  - t15.2025.01.12
  - t15.2025.03.14
  - t15.2025.03.16
  - t15.2025.03.30
  - t15.2025.04.13

  dataset_probability_val:
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

